# Generated by Django 3.2.7 on 2021-09-21 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('sen', models.SmallIntegerField()),
                ('id_number', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11)),
                ('bio', models.TextField(blank=True)),
                ('gener', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=10)),
                ('is_writor', models.CharField(choices=[('writer', 'Writer'), ('reader', 'Reader')], default='reader', max_length=10)),
                ('file_resome', models.FileField(upload_to='users/files')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
