# Generated by Django 3.2.7 on 2021-09-22 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210921_0611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-created_at',), 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='بیو'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ ایحاد'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file_resome',
            field=models.FileField(blank=True, null=True, upload_to='users/files', verbose_name='فایل رزومه'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gener',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.CharField(max_length=10, verbose_name='شماره ملی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_writor',
            field=models.CharField(choices=[('writer', 'Writer'), ('reader', 'Reader')], default='reader', max_length=10, verbose_name='ایا نویسنده'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='تماس'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sen',
            field=models.SmallIntegerField(verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
